local S
if minetest.get_modpath("intllib") then
    S = intllib.Getter()
else
    S = function(s,a,...)a={a,...}return s:gsub("@(%d+)",function(n)return a[tonumber(n)]end)end
end

local function set_livery(self, puncher, itemstack, data)
	local meta = itemstack:get_meta()
	local color = meta:get_string("paint_color")
	if color and color:find("^#%x%x%x%x%x%x$") then
		local alpha = tonumber(meta:get_string("alpha"))
		if alpha == 0 then
			data.livery = self.base_texture
		else
			data.livery = self.base_texture.."^("..self.base_livery.."^[colorize:"..color..":255)"
		end
		self:set_textures(data)
	end
end

local function set_textures(self, data)
	if data.livery then
		self.object:set_properties({textures={data.livery}})
	end
end

local bed = 'wool:white'
if  minetest.get_modpath("beds") then
	bed = 'beds:bed'
end

local door = 'default:steel_ingot'
if minetest.get_modpath("doors") then
	door = 'doors:door_steel'
end

advtrains.register_wagon("moretrains_intercity:corridor_coach_class2", {
	mesh="moretrains_intercity_corridor_coach_class2.b3d",
	textures = {"moretrains_intercity_corridor_coach_class2.png"},
	base_texture = "moretrains_intercity_corridor_coach_class2.png",
	base_livery = "moretrains_intercity_livery.png",
	set_textures = set_textures,
	set_livery = set_livery,
	drives_on={default=true},
	max_speed=20,
	seats = {
		{
			name="1",
			attach_offset={x=0, y=-2, z=17},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="2",
			attach_offset={x=0, y=-2, z=6},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="3",
			attach_offset={x=0, y=-2, z=-6},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="4",
			attach_offset={x=0, y=-2, z=-17},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
	},
	seat_groups = {
		pass={
			name = "Passenger area",
			access_to = {},
			require_doors_open=true,
		},
	},
	doors={
		open={
			[-1]={frames={x=21, y=30}, time=1},
			[1]={frames={x=1, y=10}, time=1}
		},
		close={
			[-1]={frames={x=30, y=41}, time=1},
			[1]={frames={x=10, y=20}, time=1}
		}
	},
	door_entry={-2, 2},
	assign_to_seat_group = {"pass"},
	visual_size = {x=1, y=1},
	wagon_span=3,
	collisionbox = {-1.0,-0.5,-1.0, 1.0,2.5,1.0},
	drops={"default:steelblock"},
}, S("Intercity Corridor Coach Class 2"), "moretrains_intercity_corridor_coach_class2_inv.png")

minetest.register_craft({
	output = 'moretrains_intercity:corridor_coach_class2',
	recipe = {
		{'default:steelblock', 'dye:white', 'default:steelblock'},
		{'default:glass', 'wool:blue', door},
		{'advtrains:wheel', 'default:steelblock', 'advtrains:wheel'},
	},
})

advtrains.register_wagon("moretrains_intercity:corridor_coach_class1", {
	mesh="moretrains_intercity_corridor_coach_class1.b3d",
	textures = {"moretrains_intercity_corridor_coach_class1.png"},
	base_texture = "moretrains_intercity_corridor_coach_class1.png",
	base_livery = "moretrains_intercity_livery.png",
	set_textures = set_textures,
	set_livery = set_livery,
	drives_on={default=true},
	max_speed=20,
	seats = {
		{
			name="1",
			attach_offset={x=0, y=-2, z=17},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="2",
			attach_offset={x=0, y=-2, z=6},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="3",
			attach_offset={x=0, y=-2, z=-6},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="4",
			attach_offset={x=0, y=-2, z=-17},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
	},
	seat_groups = {
		pass={
			name = "Passenger area",
			access_to = {},
			require_doors_open=true,
		},
	},
	doors={
		open={
			[-1]={frames={x=21, y=30}, time=1},
			[1]={frames={x=1, y=10}, time=1}
		},
		close={
			[-1]={frames={x=30, y=41}, time=1},
			[1]={frames={x=10, y=20}, time=1}
		}
	},
	door_entry={-2, 2},
	assign_to_seat_group = {"pass"},
	visual_size = {x=1, y=1},
	wagon_span=3,
	collisionbox = {-1.0,-0.5,-1.0, 1.0,2.5,1.0},
	drops={"default:steelblock"},
}, S("Intercity Corridor Coach Class 1"), "moretrains_intercity_corridor_coach_class1_inv.png")

minetest.register_craft({
	output = 'moretrains_intercity:corridor_coach_class1',
	recipe = {
		{'default:gold_ingot'},
		{'moretrains_intercity:corridor_coach_class2'},
	},
})


advtrains.register_wagon("moretrains_intercity:open_coach_class2", {
	mesh="moretrains_intercity_open_coach_class2.b3d",
	textures = {"moretrains_intercity_open_coach_class2.png"},
	base_texture = "moretrains_intercity_open_coach_class2.png",
	base_livery = "moretrains_intercity_livery.png",
	set_textures = set_textures,
	set_livery = set_livery,
	drives_on={default=true},
	max_speed=20,
	seats = {
		{
			name="1",
			attach_offset={x=-3.6, y=-2, z=19},
			view_offset={x=0, y=-2, z=0},
			group="pass",
		},
		{
			name="2",
			attach_offset={x=3.6, y=-2, z=8},
			view_offset={x=0, y=-2, z=0},
			group="pass",
		},
		{
			name="3",
			attach_offset={x=-3.6, y=-2, z=-9},
			view_offset={x=0, y=-2, z=0},
			group="pass",
		},
		{
			name="4",
			attach_offset={x=3.6, y=-2, z=-14.5},
			view_offset={x=0, y=-2, z=0},
			group="pass",
		},
		{
			name="5",
			attach_offset={x=-3.6, y=-2, z=-20},
			view_offset={x=0, y=-2, z=0},
			group="pass",
		},
	},
	seat_groups = {
		pass={
			name = "Passenger area",
			access_to = {},
			require_doors_open=true,
		},
	},
	doors={
		open={
			[-1]={frames={x=21, y=30}, time=1},
			[1]={frames={x=1, y=10}, time=1}
		},
		close={
			[-1]={frames={x=30, y=41}, time=1},
			[1]={frames={x=10, y=20}, time=1}
		}
	},
	door_entry={-2, 2},
	assign_to_seat_group = {"pass"},
	visual_size = {x=1, y=1},
	wagon_span=3,
	collisionbox = {-1.0,-0.5,-1.0, 1.0,2.5,1.0},
	drops={"default:steelblock"},
}, S("Intercity Open Coach Class 2"), "moretrains_intercity_open_coach_class2_inv.png")

minetest.register_craft({
	output = 'moretrains_intercity:open_coach_class2',
	recipe = {
		{'default:steelblock', 'dye:white', 'default:steelblock'},
		{'default:glass', 'wool:cyan', door},
		{'advtrains:wheel', 'default:steelblock', 'advtrains:wheel'},
	},
})


advtrains.register_wagon("moretrains_intercity:open_coach_class1", {
	mesh="moretrains_intercity_open_coach_class1.b3d",
	textures = {"moretrains_intercity_open_coach_class1.png"},
	base_texture = "moretrains_intercity_open_coach_class1.png",
	base_livery = "moretrains_intercity_livery.png",
	set_textures = set_textures,
	set_livery = set_livery,
	drives_on={default=true},
	max_speed=20,
	seats = {
		{
			name="1",
			attach_offset={x=-3.6, y=-2, z=10},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="2",
			attach_offset={x=-3.6, y=-2, z=-10},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
		{
			name="3",
			attach_offset={x=-3.6, y=-2, z=-18},
			view_offset={x=0, y=-1.7, z=0},
			group="pass",
		},
	},
	seat_groups = {
		pass={
			name = "Passenger area",
			access_to = {},
			require_doors_open=true,
		},
	},
	doors={
		open={
			[-1]={frames={x=21, y=30}, time=1},
			[1]={frames={x=1, y=10}, time=1}
		},
		close={
			[-1]={frames={x=30, y=41}, time=1},
			[1]={frames={x=10, y=20}, time=1}
		}
	},
	door_entry={-2, 2},
	assign_to_seat_group = {"pass"},
	visual_size = {x=1, y=1},
	wagon_span=3,
	collisionbox = {-1.0,-0.5,-1.0, 1.0,2.5,1.0},
	drops={"default:steelblock"},
}, S("Intercity Open Coach Class 1"), "moretrains_intercity_open_coach_class1_inv.png")

minetest.register_craft({
	output = 'moretrains_intercity:open_coach_class1',
	recipe = {
		{'default:gold_ingot'},
		{'moretrains_intercity:open_coach_class2'},
	},
})


